- hosts: all
  tasks:
   - name: Create a Deployment by reading the definition from a local file
      kubernetes.core.k8s:
       state: present
       src: /home/ec2-user/Deployment.yml


   - name: Create a Deployment by reading the definition from a local file
      kubernetes.core.k8s:
       state: present
       src: /home/ec2-user/Services.yml      
